config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  devise_for :users
  get 'users/profile' => 'users#profile'
  resources :contracts do
    member do
      post :generate_contract_signature
      post :generate_send_signature
      get :pdf
    end
    resources :steps, only: [:new, :show, :update]
    resources :payments, only: [:new, :create]
  end

  get 'pages/about' => 'pages/about'
  get 'pages/logo' => 'pages/logo'
  get 'pages/cgu' => 'pages/cgu'
  post 'test', to: "steps#test"
  post 'callbacks', to: "steps#callbacks"

  root to: 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :partners
  has_many :contracts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  skip_before_action :authenticate_user!, only: :show

  def show
  end

  def profile
    @user = current_user
    @contract = @user.contracts
    @partner = @user.partners
  end


  def set_partner
    @partner = Partner.find(params[:contract_id])
  end
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit( :email, :password)
  end



end

app/views/users/profile.html.erb
<% @user.contracts.each do |contract| %>
<div class="background">
   <div class="padded">
     <div class="about-card-content-title upcase">
      <div class="text-center">

        <h1><strong><%= contract.company_name %></strong></h1>
      </div>
    </div>
  </div>
  <div class="prof-about-card-content">
    <div class="container">
      <div class="about-card">
        <div class="about-slice">
            <div class="prof-line"></div>
              <div class="about-card-content-container">
                <div class="about-card-content-title upcase">
                  <h2>Récapitulatif des informations de la société et la levée de fonds
                     <%= link_to  generate_contract_signature_contract_path(contract), method: :post do %>
                    <div class="img-profil-edit">
                    <%= image_tag "edit.png" %>
                    </div>
                    <%end%>
                  </h2>
                </div>
                <div class="content-info">
                  <ul>
                    <li><strong>Nom de la société : </strong> <%= contract.company_name%></li>
                    <li><strong>Statut de la société :</strong> <%=contract.company_status%></li>
                    <li><strong>Adresse du siège : </strong><%=contract.headquarters_address%></li>
                    <li><strong>Capital social : </strong><%=contract.share_capital%></li>
                    <li><strong>Numéro RCS :</strong> <%=contract.rcs_number%></li>
                    <li><strong>Ville RCS : </strong><%=contract.rcs_city%></li>
                    <li><strong>Date de création :</strong> <%=contract.company_created_on%></li>
                    <li><strong>Objet social :</strong> <%=contract.company_object%></li>
                    <li><strong>Montant de la levée : </strong><%=contract.amount_to_be_raised%></li>
                    <li><strong>Engagement(s) particulier(s) :</strong> <%=contract.specific_engagment%></li>
                    <li><strong>Droits des investisseurs : </strong><%=contract.investisors_right%></li>
                    <li><strong>Juridiction en charge :</strong> <%=contract.juridiction_law%></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
    <div class="container">
      <div class="about-card">
        <div class="about-slice">
          <div class="prof-line"></div>
            <div class="about-card-content-container">
              <div class="about-card-content-title upcase">
                <h2>Récapitulatif des informations des associés
                </h2>
              </div>
               <div class="content-info">
                  <ul>
                    <% contract.partners.each_with_index do |partner, index| %>
                      <li><strong>Associé(e) <%= index + 1 %> : <%= partner.first_name %> <%= partner.last_name %></strong></li>
                        <li><strong>Email </strong> : <%=partner.email%></li>
                        <li><strong>Téléphone </strong> : <%=partner.phone%></li>
                        <li><strong>Addresse : </strong> :<%=partner.address%></li>
                        <li><strong>Né(e) le </strong> :<%=partner.birth_date%> à <%=partner.birth_location%></li>
                        <li><strong>Nationalité</strong> :<%=partner.nationality%></li>
                        <li><strong>Participation au CCA </strong> : <%=partner.founders_receivables%></li>
                    <% end %>
                  </ul>
                </div>
            </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="about-card">
        <div class="about-slice">
          <div class="prof-line"></div>
            <div class="about-card-content-container">
              <div class="about-card-content-title upcase">
                <h2>Récapitulatif des informations des investisseurs
                <%= link_to  generate_contract_signature_contract_path(contract), method: :post do %>
                    <div class="img-profil-view">
                    <%= image_tag "see.png" %>
                    </div>
                <% end %>
                 <%= link_to  generate_send_signature_contract_path(contract), method: :post do %>
                    <div class="img-profil-send">
                    <%= image_tag "send.png" %>
                    </div>
                <% end %>
                </h2>
                </div>
                  <div class="content-info">
                    <ul>
                      <% contract.investors.each_with_index do |investor, index| %>
                        <li><strong>Investisseur: <%= index + 1 %> : <%= investor.first_name %> <%= investor.last_name %> </li></strong>
                        <li><strong>Adresse Mail</strong> : <%=investor.email%></li>
                        <li><strong>Nationalité</strong> : <%=investor.nationality%></li>
                        <li><strong>Adresse</strong> : <%=investor.address%></li>
                        <li><strong>Montant investi</strong> : <%=investor.amount_raised%></li>
                        <li><strong>Né(e) le</strong> : <%=investor.birthdate%> à <%=investor.birthplace%> </li>
                        <li><strong>Valorisation cap </strong> : <%=investor.valo_floor%></li>
                        <li><strong>Valorisation floor </strong> : <%=investor.valo_cap%></li>
                        <li><strong>Décote </strong> :<%=investor.rate_drop%></li>
                      <% end %>
                    </ul>
                  </div>
            </div>
          </div>
      </div>
    </div>
  </div>


    <div class="text-center padded upcase">

      <% if contract.state == 'pending' %>
          <%= link_to 'Acheter', new_contract_payment_path(contract), class: 'btn btn-primary' %>
        <% else %>
          <%= link_to 'Télécharger le contrat', contract_path(contract), class: 'btn btn-primary' %>
        <% end %>
    </div>
     <% end %>

 <!--  <div class="header_menu">
    <ul class="header_menu horizontal_list">
      <li><a class="no_border purple" href="#">Profile</a></li>
      <li><a href="#">Contrats</a></li>
      <li><a href="#">Modifier</a></li>
      <li><a href="#">Générer un nouveau contrat</a></li>
    </ul>
  </div> -->


</div>