config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  devise_for :users
  get 'users/profile' => 'users#profile'
  resources :contracts do
    member do
      post :generate_contract_signature
      post :generate_send_signature
      get :pdf
    end
    resources :steps, only: [:new, :show, :update]
    resources :payments, only: [:new, :create]
  end

  get 'pages/about' => 'pages/about'
  get 'pages/logo' => 'pages/logo'
  get 'pages/cgu' => 'pages/cgu'
  post 'test', to: "steps#test"
  post 'callbacks', to: "steps#callbacks"

  root to: 'pages#home'

end

app/views/pages/about.html.erb
  <div class="title-slice">
    <div class="title-slice-container">
      <div class="title">
        L'équipe
      </div>
      <div class="sub-title">
        Arthur, Emmanuelle et Maxime se sont rencontré au Wagon.
      </div>
    </div>
  </div>


 <div class="padded">
    <div class="container text-center" id="features">
      <div class="cards">

        <div class="card-container">
          <div class="card yellowc" >
            <%= image_tag "arthur.jpg", class: "img-circle"%>
            <h2>Arthur</h2>
            <p><strong>Arthur, après une ecole de commerce.</strong></p>
          </div>
        </div>
        <div class="card-container">
          <div class="card yellowc">
            <%= image_tag "emma.png", class: "img-circle"%>
            <h2>Emmanuelle</h2>
            <p><strong>Apres une carière de 2ans dans la Hi-tech, Emmanuelle à décider de se former a la programation. </strong></p>
          </div>
        </div>
        <div class="card-container">
          <div class="card yellowc">
            <%= image_tag "max.png", class: "img-circle"%>
            <h2>Maxime</h2>
            <p><strong>Entrepreneur depuis deja 2 ans Maxime...</strong></p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/cgu.html.erb
  <div class="title-slice">
    <div class="title-slice-container">
      <div class="title">
        Conditions Générales d’Utilisation
      </div>
      <div class="sub-title">
        Le guide pour tout comprendre.
      </div>
    </div>
  </div>
  <div class="container">
  <div class="about-slice">
    <div class="about-card-container">
      <div class="about-card">
 <!--        <div class="line"></div> -->
        <div class="about-card-content-container">
          <div class="about-card-content-title">
            Bsa Accord d’Investissement Rapide, consultation juridique
          </div>
          <div class="about-card-content">
            <li>Votre attention est spécifiquement attirée sur le fait que l’ensemble des documents mis à votre disposition constituent de simples exemples, qui ne concernent que la conclusion d’un Accord d’Investissement Rapide dans une société par actions simplifiée.</li>

            <li>Ce modèle d’investissement convient aux sociétés en phase d’amorçage
            et qui ne font pas d’offre au public de titres financiers.
            Attention : Il peut ne pas être éligible à certaines réductions d’impôts (ISF, PME etc.)</li>

            <li>Il ne constitue en aucune manière un avis ou une consultation juridique.
            Nous vous recommandons en toutes circonstances de solliciter l’avis ou l’assistance d’un avocat pour la mise en œuvre d’un Accord d’Investissement Rapide.
            Le AIR repose sur l'utilisation d'un bon de soucription d'actions (BSA), dont les principes de fonctionnement s'inspirent du mécanisme bien rodé des BSA Ratchet, mais en sens inverse.</li>

          </div>
        </div>
      </div>
    </div>
    <div class="about-card-container">
      <div class="about-card">
        <div class="line"></div>
        <div class="about-card-content-container">
          <div class="about-card-content-title">
            Mentions légales
          </div>
          <div class="about-card-content">
            <li>Boomerang n'est pas un cabinet d'avocats et ne fournit aucun conseil juridique. Conformément à la réglementation applicable, Boomerang permet aux utilisateurs de créer eux-mêmes des actes juridiques. Conformément à la réglementation applicable et, en particulier, aux dispositions de la loi du 31 décembre 1971 modifiée, Boomerang, ses dirigeants, salariés et partenaires n’exercent pas d’activité de consultation en matière juridique, de rédaction d’actes sous seing privé ou de représentation. </li>
            <li>Vous reconnaissez que vous créez vous-mêmes vos Documents, sans le conseil d’un professionnel du droit. Pour toute consultation juridique, vous reconnaissez qu’il est obligatoire de se rapprocher (par l’intermédiaire du Site ou par tout autre moyen) d’un avocat ou de toute autre personne habilitée par la loi à effectuer des prestations de conseil juridique. </li>
            <li>Le Site et/ou les Services proposés sur le Site ne sauraient en aucun cas se substituer à une consultation d’avocat.</li>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/pages/home.html.erb
<div class="banner text-center " style="background-image: url('<%= image_path "startup.png" %>')">
  <div class="banner-gradient"></div>
  <div class="banner-content marged-header filtrer">
    <div class="banner-name">
      <div class="banner-name-company">
        boomerang
      </div>
      <div class="banner-name-logo"><%= image_tag "logow.png" %></div>
    </div>


    <div class="content-text">
      <p><strong>Réalisez votre première levée de fonds.</strong></p>
      <p><strong>Créez un contrat qui protège vos investisseurs & votre startup.</strong></p>
    </div>
     <%= link_to t("btn btn-primary btn-lg", default: "COMMENCEZ GRATUITEMENT"), new_contract_path(), class: "navbar-wagon-item navbar-wagon-button btn btn-primary" %>
  </div>
</div>


<div id="offres">
  <div class="padded">
    <div class="container text-center" id="features">
      <div class="cards">

        <div class="card-container">
          <div class="card yellowc" >
            <%= image_tag "contrat.png" %>
            <h2>CONTRATS </br>BSA AIR</h2>
            <p><strong>Bénéficiez d'un contrats spécialement rédigé pour les levées de fonds early-stage simple et robuste.</strong></p>
          </div>
        </div>
        <div class="card-container">
          <div class="card yellowc">
            <%= image_tag "signature.png" %>
            <h2>SIGNATURES EN LIGNE</h2>
            <p><strong>Une signature électronique reconnu juridiquement en Europe et aux Etat-Unis.</strong></p>
          </div>
        </div>
        <div class="card-container">
          <div class="card yellowc">
            <%= image_tag "securite4.png" %>
            <h2>GARANTIE</h2>
            <p><strong>Vos contrats sont conservés et accessible sur votre profil Boomerang pendant 5 ans.</strong></p>
          </div>
        </div>
        <div class="card-container">
          <div class="card yellowc">
            <%= image_tag "authenticite.png" %>
            <h2>AUTHENTICITE DES CONTRATS</h2>
            <p><strong>Vos contrats et leurs signatures sont uniques et authentifiés grace à la cryptologie HelloSign.</strong></p>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<div id="apropos">
  <div class="title-slice">
    <div class="title-slice-container">
      <div class="title">
        Les Avantages du BSA AIR
      </div>
      <div class="sub-title">
        Les contrats Bsa Air permettent aux start-up de lever de l'argent facilement, sans la lourdeur juridique d'une levée de fonds classique
      </div>
    </div>
  </div>
  <div class="container">
    <div class="about-slice">
      <div class="about-card-container">
        <div class="about-card">
          <div class="about-card-image"><%= image_tag "valo.png" %></div>
          <div class="about-card-content-container">
            <div class="about-card-content-title">
              Simplification de la problématique de valorisation de la start-up
            </div>
            <div class="about-card-content">
              La question de la <strong>valorisation</strong>: c'est un des <strong>points majeurs de friction</strong> entre les fondateurs de la start-up et les potentiels investisseurs
            </div>
          </div>
        </div>
      </div>
      <div class="about-card-container">
        <div class="about-card">
          <div class="about-card-image"><%= image_tag "time.png" %></i></div>
          <div class="about-card-content-container">
            <div class="about-card-content-title">
              Gain de temps
            </div>
            <div class="about-card-content">
              Les Bsa Air font gagner un temps précieux: <strong>100 heures</strong> c'est le temps moyen estimé pour le montage juridique d'une levée de fonds classique
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="title-slice">
    <div class="title-slice-container">
      <div class="title">
        En quoi consiste les contrats Bsa Air?
      </div>
      <div class="sub-title">
        Découvrez les bons de souscription d'actions avec plus de légèreté : AIR (Accord d'Investissement Rapide)
      </div>
    </div>
  </div>
  <div class="container">
  <div class="about-slice">
    <div class="about-card-container">
      <div class="about-card">
        <div class="line"></div>
        <div class="about-card-content-container">
          <div class="about-card-content-title">
            Des Bsa Ratchet allégés...
          </div>
          <div class="about-card-content">
            <li>Les Bsa Ratchet sont des outils utilisés par les investisseurs pour <strong>corriger la valorisation</strong> sur laquelle ils sont rentrés </li>
            <li>Concrètement, les Bsa Ratchet sont des actions supplémentaires auxquelles l'investisseur <i>early stage</i> peut souscrire à un prix avantageux s'il est rentré sur une VE qui a diminué lors d'un précédent tour</li>
            <li>Les Bsa Ratchet permettent aux actionnaires, lors d'une augmentation de capital, de souscrire à de nouvelles actions (à un prix préférentiel fixé à l'avance), jusqu'à une date déterminée.</li>
          </div>
        </div>
      </div>
    </div>
    <div class="about-card-container">
      <div class="about-card">
        <div class="line"></div>
          <div class="about-card-content-container">
            <div class="about-card-content-title">
              ... D'une grande souplesse juridique
            </div>
            <div class="about-card-content">
              <li>Le principe des contrats Bsa Air est de <strong>décaler la valorisation de l'entreprise dans le temps</strong></li>
              <li>Pour baser une levée de fonds <i>early stage</i> sur des Bsa Air, il suffit à l’entreprise d’émettre au profit de l’investisseur un BSA unique (prix de souscription = montant de l'investissement).</li>
              <li>La prochaine levée auprès d'un fonds de capital risque déterminera une valorisation précise</li>
              <li>Le nombre d'action auquel aura droit l'investisseur sera déterminé à <strong>posteriori</strong> en fonction de la valorisation retenue lors de la <strong>levée de fonds ultérieure</strong></li>
            </div>
          </div>
      </div>
    </div>
  </div>
  </div>



<div id="faq">
  <div class="title-slice">
    <div class="title-slice-container">
      <div class="title">
        Comprendre en Vidéo
      </div>
      <div class="sub-title">
        “There are two ‘i’s’ in Fundraising – they should stand for inspiration and innovation, not imitation and irritation.”
      </div>
    </div>
  </div>
  <div class="container">
    <div class="about-slice">
        <div class="about-card center-vid">
          <div class="about-card-content-container">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/PGnA05XK4Ho" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
    </div>
  </div>
</div>


  <div class="title-slice">
    <div class="title-slice-container">
      <div class="title">
        Un exemple
      </div>
      <div class="sub-title">
        Les associés de la start-up Picly souhaitent rapidement faire<strong> une première levée de fonds</strong> en <i>love-money</i>. Mr Sponsz, séduit par le projet, souhaite investir. Pour sécuriser l'investissement, Picly et Mr Sponsz s'appuyent sur les contrats <strong>BSA AIR</strong>.
      </div>
    </div>
  </div>
  <div class="container">
    <div class="about-slice">
      <div class="about-card-container-ex">
        <div class="about-card">
          <div class="about-card-image"><%= image_tag "love.png" %></i></div>
          <div class="about-card-content-container">
            <div class="about-card-content-ennoncer">
              <li>Montant levé: 200 000 € </li>
              <li>Valorisation floor: 1M € </li>
              <li>Valorisation cap: 3,5M €</li>
              <li>Taux de décote: 30%</li>
            </div>
            <div class="about-card-content-case">
              <div class="about-card-content-cas">
                <div class="about-card-content-cas-title">
                  Cas 1: 1 an après, levée de fond de 1,5 M€ auprès d'Isai Capital
                </div>
                <div class="about-card-content-cas-reso">
                  <li> Cas ou la valorisation retenue par Mr Sponsz, après application du taux de décôte, est incluse dans le tunnel de valorisation</li>
                  <li><strong>Valorisation retenue</strong> par Isai: 4,5 M€</li>
                  <li><strong>Valorisation retenue</strong> par Mr Sponsz (après application du taux de décote de 30%): 3,15 M€ (70% de 4,5M €)</li>
                  <li>Mr Sponsz investit 200 000 € sur 3,15M € (et non pas sur 4,5 M €!). Il convertit son Bsa Air en action.</li>
                </div>
              </div>
              <div class="about-card-content-cas">
                <div class="about-card-content-cas-title">
                  Cas 2: 1 an après, levée de fond de 1,5 M€ auprès d'Isai Capital
                </div>
                <div class="about-card-content-cas-reso">
                   <li> Cas ou la valorisation retenue par Mr Sponsz, après application du taux de décôte, est hors du tunnel de valorisation, augmentant le taux de décôte</li>
                  <li><strong>Valorisation retenue</strong> par Isai: 7 M€</li>
                  <li> L'application du taux de décote implique une <strong>valorisation de 4,9 M€</strong> : c'est au dessus de la valorisation cap déterminée dans le Bsa Air (3,5M€)</li>
                  <li> Au moment de convertir son Bsa Air en action, Mr Sponsz retient donc la <strong>valorisation cap</strong>: 3,5 M€.
                  <li>Mr Sponsz investit 200 000 € sur une valorisation de 3,5M € (et non pas sur 7 M €!)
                  <li> Le taux de décôte retenu est donc de 50% et non plus de 30%!</li>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/logo.html.erb
<%= image_tag "logob.png" %>