config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  devise_for :users
  get 'users/profile' => 'users#profile'
  resources :contracts do
    member do
      post :generate_contract_signature
      post :generate_send_signature
      get :pdf
    end
    resources :steps, only: [:new, :show, :update]
    resources :payments, only: [:new, :create]
  end

  get 'pages/about' => 'pages/about'
  get 'pages/logo' => 'pages/logo'
  get 'pages/cgu' => 'pages/cgu'
  post 'test', to: "steps#test"
  post 'callbacks', to: "steps#callbacks"

  root to: 'pages#home'

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_contract

  def new
  end

  def create
    @price = @contract.price_cents

    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email: params[:stripeEmail]
    )
    # You should store this customer id and re-use it.

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount:       @price,  # in cents
      description:  "Payment for contract #{@contract.id}",
      currency:     'eur'
    )

    @contract.update(payment: charge.to_json, state: 'paid')

    redirect_to users_profile_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_contract_payment_path(@contract)
  end




private

  def set_contract
    @contract = Contract.where(state: 'pending').find(params[:contract_id])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="background padded-btn">
  <div id="faq">
    <div class="title-slice">
      <div class="title-slice-container">
        <div class="title">
          <h2>Le payement</h2>
        </div>
        <div class="sub-title">
          Chez Boomerang achetez vos contrats à un prix unique et générez autant d'exemplaires que vous le souhaitez!
        </div>
      </div>
    </div>
    <div class="container">
      <div class="about-slice padlog">
          <div class="about-card center-vid">
            <div class="about-card-content-container pay">
                <%= form_tag contract_payments_path(@contract) do %>
                <article>
                  <label class="price">
                    <span>Price: <%= humanized_money_with_symbol(@contract.price) %></span>
                  </label>
                </article>

                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-name="my-contract"
                  data-description="Contract <%= @contract.id %>"
                  data-amount="<%= @contract.price_cents %>"
                  data-currency="EUR"></script>
              <% end %>

            </div>
            <div class="container">
           <div class="row">
              <div class="col-xs-12">

    </div>
  </div>
</div>

          </div>
      </div>
    </div>
  </div>
</div>